name = "ttstock"
main = "worker.js"
compatibility_date = "2026-04-01"
compatibility_flags = ["nodejs_compat"]

# Serve static assets từ thư mục dist
assets = { directory = "./dist", binding = "ASSETS" }

[vars]
ERP_TARGET = "https://erp.mte.vn"
